name: Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install NPM Dependencies
      run: npm install
    - name: Build assets
      run: npm run build
    - name: Stage Files
      run: git add -f dist
    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git commit -m "Build for deploy"
    - name: Publish
      run: |
        git subtree split --prefix dist -b deploy
        git push -f origin deploy:deploy